import Head from "next/head";

import styles from "../styles/Home.module.css";
import { Header } from "../common/Header";
// globalStyles.js
import styled, { createGlobalStyle } from "styled-components";

const GlobalStyle = createGlobalStyle`
  body {
    margin: 0;
    padding: 0;

  }
  * {
    box-sizing: border-box;
  }
`;

const MainWrapper = styled.div`
  width: 100%;
`;

export default function Home() {
  return (
    <MainWrapper>
      <GlobalStyle />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />

        <p className={styles.description}>
          大家一起當人造人！
          <code className={styles.code}>pages/index.tsx</code>
        </p>
      </main>
    </MainWrapper>
  );
}
